def multiples_of():
    # If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3 and 5, 6, 9.
    # The sum of these multiples is 23.
    # Find the sum of all the multiples of 3 or 5 below 1000.
    n1 = int(input("What number: "))

    def mult_of(base, limit, x=1, collected=None):
        if collected is None:
            collected = []
        n2 = base * x
        if n2 < limit:
            collected.append(n2)
            return mult_of(base, limit, x + 1, collected)
        else:
            return collected

    total_3 = mult_of(3, n1)
    total_5 = mult_of(5, n1)

    all_mult = sorted(set(total_5 + total_3))
    total = sum(all_mult)
    print(f"{all_mult}")
    print(f"Total:\n{total}")
    main()

def fibonacci_numbers():
    # Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    # 1,2,3,5,8,13,21,34,55,89
    # By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    seq = [1, 2]
    def sequence():
        last_1 = seq[-1]
        last_2 = seq[-2]
        add_var = last_1 + last_2
        seq.append(add_var)
        if last_1 <= 4000000:
            sequence()
        else:
            even_numbers_list = [num for num in seq if num % 2 == 0]
            print(even_numbers_list)
            total = sum(even_numbers_list)
            print(f"total of all even number in fibonacci sequence before the limit of 4 million is {total}")
    sequence()
    main()

def prime_factorial():
    # The prime factors of 13,195 are 5,7,13 and 29.
    # What is the largest prime factor of the number 600,851,475,143?
    n = int(input("What number: "))
    factors = []
    x = 2
    while x * x <= n:
        if n % x == 0:
            factors.append(x)
            n //= x
        else:
            x += 1
    if n > 1:
        factors.append(n)

    print(f"Prime factors of {n}: {factors}")
    main()

def palindrome():
    from tqdm import tqdm
    print("*less than 8 digits please*")
    def is_palindrome(number):
        #ChatGPT assisted**
        return str(number) == str(number)[::-1]

    def largest_palindrome(x):
        #ChatGPT assisted**
        max_num = 10 ** x - 1
        min_num = 10 ** (x - 1)
        largest = 0
        factors = (0, 0)

        for i in tqdm(range(max_num, min_num - 1, -1), desc="Checking numbers"):
            for j in range(i, min_num - 1, -1):
                product = i * j
                if product <= largest:
                    break
                if is_palindrome(product):
                    largest = product
                    factors = (i, j)

        print(f"\nLargest palindrome from the product of two {x}-digit numbers: {largest}")
        print(f"Factors: {factors[0]} × {factors[1]}")

    n = int(input("Enter the number of digits: "))
    largest_palindrome(n)
    main()

def smallest_multiple():
    # 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
    # What is the smallest positive number that is evenly divisible by all the numbers from 1 to 20?

    range_size = input("Biggest number in range: ")
    print(f"for the smallest positive number that is evenly divisible by all the numbers from 1 to {range_size}")

    def build_range(x=0):
        range = []
        while not range[-1] == range_size:
            x+=1
            range.append(x)
        return range

    def check(n):
        print()




def main():
    #Main menu of all Functions
    print("----------")
    print("Problem 1: 3 and 5 multiples\n"
          "Problem 2: Fibonacci Numbers sum of all even numbers before 4 million \n"
          "Problem 3: Prime number factorial\n"
          "Problem 4: Largest palindrome from the product of x amount of digits\n"
          "Problem 5: Smallest multiple divisible with all the numbers in a range")
    menu = input("which problems do you want to see (type '0' to exit): ")
    print("----------")

    if menu == "1":
        multiples_of()
    elif menu == "2":
        fibonacci_numbers()
    elif menu == "3":
        prime_factorial()
    elif menu == "4":
        palindrome()
    elif menu == "5":
        smallest_multiple()
    elif menu == "0":
        print("exiting")
        exit()
    else:
        print("Issue with answer; try again.")
        main()

main()